DROP TABLE IF EXISTS USUARIO;
CREATE TABLE IF NOT EXISTS USUARIO (
    id INT AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    senha VARCHAR(50) NOT NULL,
    ativo INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS  AUTORIDADE (
    id INT AUTO_INCREMENT NOT NULL,
    username VARCHAR(45) NOT NULL,
    authority VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
    
);